# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Guarded' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for Guarded
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'Nuke', '~> 5.0'

end

